#!/bin/sh -v
# copy files source to buildroot to the fast compile

if [ ! -n "$1" ]; then
    echo "No input ID commit at '\$1'."
	exit 1
fi

cp *.c ../knot-gateway-buildroot/output/build/knot-hal-driver-$1/
cp *.cpp ../knot-gateway-buildroot/output/build/knot-hal-driver-$1/
cp *.h ../knot-gateway-buildroot/output/build/knot-hal-driver-$1/
cp src/*.c ../knot-gateway-buildroot/output/build/knot-hal-driver-$1/src
cp src/*.h ../knot-gateway-buildroot/output/build/knot-hal-driver-$1/src
cp src/nrf24l01/*.c ../knot-gateway-buildroot/output/build/knot-hal-driver-$1/src/nrf24l01
cp src/nrf24l01/*.h ../knot-gateway-buildroot/output/build/knot-hal-driver-$1/src/nrf24l01
cp src/spi/*.c ../knot-gateway-buildroot/output/build/knot-hal-driver-$1/src/spi
cp src/spi/*.h ../knot-gateway-buildroot/output/build/knot-hal-driver-$1/src/spi
cp configure.ac ../knot-gateway-buildroot/output/build/knot-hal-driver-$1/
cp Makefile.am ../knot-gateway-buildroot/output/build/knot-hal-driver-$1/
cp src/Makefile.am ../knot-gateway-buildroot/output/build/knot-hal-driver-$1/src
cp src/nrf24l01/Makefile.am ../knot-gateway-buildroot/output/build/knot-hal-driver-$1/src/nrf24l01
cp src/spi/Makefile.am ../knot-gateway-buildroot/output/build/knot-hal-driver-$1/src/spi
