# Target: KNOT Driver Library
# KNOT Driver Library is a lightweight C library built to use
# minimal CPU and memory resources.
INCLUDES += -I./src
INCLUDES += -I./src/spi
INCLUDES += -I./src/nrf24l01
